services:
    resomedia_entity_history.historization_manager:
        class: Resomedia\EntityHistoryBundle\Services\HistorizationManager
        arguments: ["@doctrine.orm.entity_manager", "%resomedia_entity_history.user_property%", "%resomedia_entity_history.class_history%", "@security.authorization_checker", "@security.token_storage", "%resomedia_entity_history.entities%", "@annotation_reader"]
