services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    history.annotations.reader:
        class: Doctrine\Common\Annotations\AnnotationReader
    Doctrine\Common\Annotations\Reader:
        alias: history.annotations.reader
    Resomedia\EntityHistoryBundle\Services\HistorizationManager:
        arguments: ['%resomedia_entity_history.user_property%', '%resomedia_entity_history.class_history%', '%resomedia_entity_history.entities%', '@security', '@annotation_reader', '@doctrine.orm.entity_manager']
    resomedia_entity_history.historization_manager:
        class: Resomedia\EntityHistoryBundle\Services\HistorizationManager
    #resomedia_entity_history.subscriber:
        #class: Resomedia\EntityHistoryBundle\Subscribers\HistorizationSubscriber
        #arguments: ["@resomedia_entity_history.historization_manager"]
        #tags:
            #-  { name: doctrine.event_subscriber }